export { DashboardScreen } from "./dashboard/DashboardScreen";
export type {
    ClockTile,
    DashboardChunkCoordinate,
    DashboardConfig,
    DashboardEmergency,
    DashboardGrid,
    DashboardSeverity,
    DashboardStatus,
    DashboardTile,
    DashboardTileContent,
    DashboardTileLayout,
    DashboardTileSlot,
    DashboardTileType,
    IframeTile,
    MetricTile,
    NoticeItem,
    NoticeListTile,
    RotatingTileGroup,
    ServiceStatusItem,
    ServiceStatusTile,
    TextTile,
} from "./dashboard/types";
