import type { ScreenInfo } from "../../api";

export const mockScreens: ScreenInfo[] = [
    {
        tablo_id: "lobby-main",
        name: "Холл, главный вход",
        group_name: "Холлы",
        is_online: true,
        last_seen_at: "2026-06-07T03:42:00+05:00",
        assigned_template_id: 1,
        assigned_template_name: "Основной вертикальный",
        assigned_at: "2026-06-07T02:50:00+05:00",
    },
    {
        tablo_id: "lobby-service",
        name: "Холл, сервисный вход",
        group_name: "Холлы",
        is_online: true,
        last_seen_at: "2026-06-07T03:40:00+05:00",
        assigned_template_id: 1,
        assigned_template_name: "Основной вертикальный",
        assigned_at: "2026-06-07T02:50:00+05:00",
    },
    {
        tablo_id: "parking-p1",
        name: "Паркинг P1",
        group_name: "Паркинг",
        is_online: false,
        last_seen_at: "2026-06-06T22:15:00+05:00",
        assigned_template_id: 3,
        assigned_template_name: "Паркинг и навигация",
        assigned_at: "2026-06-06T19:10:00+05:00",
    },
    {
        tablo_id: "entrance-2",
        name: "Подъезд 2",
        group_name: "Подъезды",
        is_online: true,
        last_seen_at: "2026-06-07T03:43:00+05:00",
        assigned_template_id: null,
        assigned_template_name: null,
        assigned_at: null,
    },
    {
        tablo_id: "display-test",
        name: "Тестовый экран",
        group_name: null,
        is_online: false,
        last_seen_at: null,
        assigned_template_id: 2,
        assigned_template_name: "Информационный",
        assigned_at: "2026-06-05T14:20:00+05:00",
    },
];